version: "3.9"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      NEO4J_URI: "bolt://db:7687"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./nodemon.json:/app/nodemon.json
    command: npm run dev

  db:
    image: neo4j:5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    env_file:
      - .env
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_server_config_strict__validation_enabled: "false"
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
